---
title: '[github actions]Error: Process completed with exit code 5.'
private: false
tags:
  - python
  - GitHub Actions
  - pytest
updated_at: '2025-06-01T01:52:57.667Z'
id: null
organization_url_name: null
slide: false
---

## エラー内容

```
Run pytest
  pytest
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib
============================= test session starts ==============================
platform linux -- Python 3.7.17, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/runner/work/aws-lambda-test/aws-lambda-test
collected 0 items

============================ no tests ran in 0.01s =============================
Error: Process completed with exit code 5.
```

## 原因
pytestのテスト対象がないと発生する

## 対応策
`assert文`が漏れている
そもそもテストする必要がないならgithub actions 側で
pytestのstepを削除する